export const AppStrings = {
    USERNAME_EXISTS: "username is already exist.",
    EMAIL_EXISTS: "email is already registered.",
    MOBILE_EXISTS: "mobile no is already exist.",
    TOKEN_REQUIRED: "token is required",
    EMAIL_MOBILE_ALREADY_EXITS:"mobile no or email is already exist.",
    MOBILE_IS_NOT_VALID: "mobile no is not valid",
    USERNAME_NOT_EXISTS: "username does not exist.",
    EMAIL_NOT_EXISTS: "email does not exist.",
    MOBILE_NOT_EXISTS: "mobile does not exist.",
    INVALID_PASSWORD: "invalid credentials entered or no such user found.",
    BLACKLISTED_TOKEN: "blacklisted token.",
    INVALID_SESSION: "your session is not valid.",
    INVALID_REQUEST: "invalid request.",
    UNAUTHORIZED: "full authentication is required to access this resource",
    INVALID_PAYLOAD: "couldn't process data",
    USERNAME_EMAIL_MOBILE_REQUIRED: "username, email or mobile is required.",
    EMAIL_MOBILE_REQUIRED: "email or mobile is required.",
    OTP_SENT: "otp sent successfully.",
    USER_CREDENTIAL_DOES_NOT_MATCH: "invalid credentials entered or no such user found.",
    DECRYPT_DATA_IS_REQUIRED: "decrypt data is required.",
    CHECK_MAIL: "check mail for otp.",
    CHECK_PHONE: "check phone for otp.",
    INVALID_REASON: "invalid reason type.",
    ALREADY_ADDED_REFERENCE: "already added reference",
    USER_PROFILE_COMPLETED: "user profile register successfully",
    SOMETHING_WENT_WRONG: "something went wrong",
    STATUS_UPDATED_SUCCESSFULLY: "status update successfully",
    ID_LIMIT_UPDATED_SUCCESSFULLY: "id verify limit update successfully",
    REFERENCES_ADDED_SUCCESSFULLY: "references added successfully",
    DOCUMENT_SUBMITTED_SUCCESSFULLY: "document submitted successfully",
    TERMINATE_ANOTHER_MOBILE_SESSION: "another session is used by other device",
    ALREADY_REGISTER: "you have already register with email",
    ALREADY_REGISTER_MOBILE: "you have already register with mobile",
    PLEASE_UPLOAD_IMAGE: "please uploaded image or video.",
    USER_IS_NOT_GUEST: "user is not guest",
    GUEST_IS_NOT_ALLOWED_TO_ACCESS_PATH: "guest user is not allowed to access this path",
    NOT_FOR_GUEST: "refresh token is not for guest",
    INVALID_DEVICEID: "invalid device id",
    MOBILE_REQUIRED: "mobile is required.",
    OTP_TOKEN_REQUIRED: "otp and token is required.",
    INVALID_OTP: "invalid otp.",
    INVALID_DEVICE: "invalid device.",
    OTP_EXPIRED: "otp expired.",
    OTP_VERIFIED: "otp verified.",
    OTP_NOT_MATCH: "otp does not match.",
    OTP_ALREADY_VERIFIED: "otp already verified.",
    OTP_REQUEST_LIMIT: "otp request limit reached.",

    USER_NOT_FOUND: "User not found.",
    INVALID_TOKEN: "invalid token.",
    TOKEN_EXPIRED: "token expired.",
    EMPLOYEE_ALREADY_ADDED: "this employee is already part of other business.",
    SET_LOCATION: "location not found.",

    BLOCK_EVENT_NOT_FOUND: "block event not found.",
    EVENT_DELETE: "event delete successfully.",

    PASSWORD_CHANGED: "password changed successfully.",
    USERID_MISSING: "userid is missing.",
    INCORRECT_OTP: "entered otp is incorrect.",
    USER_TYPE_MISMATCH: "user type mismatch.",

    PROVIDER_TYPE_MISSING_OR_INVALID: "provider type is missing or invalid.",
    USER_NOT_PROVIDER: "user is not a provider.",
    USER_NOT_SEEKER: "user is not a seeker.",
    PROFILE_UPDATED: "profile updated successfully.",
    SEEKER_INTRO_UPDATED: "seeker intro updated successfully.",
    SEEKER_INTRO_SAVED: "seeker intro saved successfully.",
    USER_DOES_NOT_MATCH: "user type does not match.",
    INVALID_ID: "invalid id.",
    TIME_INVALID: "time is invalid.",

    IMAGE_UPLOADED: "image uploaded successfully.",
    IMAGE_NOT_FOUND: "image not found.",
    IMAGE_NOT_UPLOADED: "image not uploaded.",
    FILE_NOT_UPLOADED: "file not uploaded.",
    FILE_FORMAT_NOT_SUPPORTED : "file format not supported",
    FILE_NOT_FOUND: "file not found.",
    VIDEO_NOT_UPLOADED: "video not uploaded.",
    VIDEO_NOT_FOUND: "video not found.",

    AUDIO_NOT_FOUND: "audio not found.",
    AUDIO_NOT_UPLOADED: "audio not uploaded.",
    AUDIO_UPLOADED: "audio uploaded successfully.",

    PROFILE_FETCHED: "profile fetched successfully.",

    SEEKER_ID_MISSING: "seeker id is missing.",
    USER_MUST_BE_PROVIDER_OR_SEEKER: "user must be a provider or seeker.",


    JOB_POSTED_SUCCESSFULLY: "job posted successfully.",
    JOB_NOT_FOUND: "job not found.",
    JOB_NOT_FOUND_WITH_SEEKER: "job not found with this seeker.",

    JOB_ID_REQUIRED: "job id is required.",
    JOB_TIME_INVALID: "job time is invalid.",
    JOB_APPLIED_SUCCESSFULLY: "job applied successfully.",
    JOB_APPLIED_ALREADY: "job applied already.",
    JOB_APPLIED_ALREADY_FOR_SAME_TIME: "another job is applied by you for same time.",
    JOB_NOT_OPEN: "job is not open.",
    JOB_FINAL_AMOUNT_IS_INCORRECT: "job final amount is incorrect",
    PARAMS_IS_REQUIRED: "paramater is required",

    JOB_APPLIED_ALREADY_OR_SEEKER_ALREDY_REQUESTED: "job applied already or seeker already requested.",
    SEEKER_ALREDY_REQUESTED: "seeker already requested for this job.",
    JOB_NOT_ASSIGNED: "this job is not assigned to you.",

    ALREADY_APPLIED_FOR_THIS_JOB: "you have already applied for this job.",
    JOB_EXPIRED: "job expired.",
    JOB_ASSIGNED_SUCCESSFULLY: "job assigned successfully.",
    JOB_NOT_ASSIGNED_TO_PROVIDER: "job is not assigned to provider.",

    APPLICANT_ID_REQUIRED: "applicant id is required or not valid.",
    ACTION_REQUIRED: "action is required or not valid.",
    JOB_STATUS_UPDATED_SUCCESSFULLY: "job status updated successfully.",
    JOB_CANCELLED_SUCCESFULLY: "job cancelled successfully.",
    JOB_ACTION_TIME_EXPIRE: "job action time expire.",

    INVALID_LIST_TYPE: "invalid list type.",
    INVALID_DETAIL_TYPE: "invalid details type.",
    RATING_SUCCESSFULLY_SENT: "rating successfully sent.",
    ALREADY_RATED: "you have already rated this field.",

    RATING_NOT_FOUND: "rating not found.",
    NOT_AUTHORIZED: "you are not authorized to perform this action.",
    RATING_UPDATED_SUCCESSFULLY: "rating updated successfully.",

    DISPUTE_SUCCESS: "dispute successfully raised.",
    ALREADY_DISPUTED: "you have already disputed this field.",
    NO_JOB_ASSIGNED_WITH_THIS_ID: "no job assigned with this id.",
    DISPUTE_NOT_FOUND: "dispute not found.",
    DISPUTE_ID_REQUIRED: "dispute id is required.",

    USER_NOT_ELIGIBLE_TO_APPLY_JOB: "you are not eligible to apply for this job.",
    USER_NOT_ELIGIBLE_FOR_HIRING: "you are not eligible for hire to this job.",

    STATUS_NOT_ALLOWED: "status not allowed to be updated.",
    JOB_REQUIREMENT_IS_FULFILLED: "job requirement is fulfilled.",
    JOB_START_TIME_INVALID: "job start time is must be greater than current time.",
    JOB_IS_NOT_AVAILABLE_FOR_HIRING: "job is not available for hiring.",

    WALLET_CREATED: "wallet created successfully.",
    WALLET_ALREADY_EXIST: "wallet already exist.",
    WALLET_NOT_EXIST: "wallet does not exist.",
    WALLET_BALANCE_IS_INSUFFICIENT: "you don't have enough balance to pay admin fees,please add money in your wallet.",
    AMOUNT_MISSING: "amount is missing.",
    WALLET_CAN_NOT_INTEGRETED: "wallet can not integreated this time",

    SERVER_ERROR: "server error. please try again later.",
    RAZORPAY_ERROR: "razorpay error. please try again later.",

    AGE_NOT_VALID: "age must be greater than 15.",
    DOB_NOT_VALID: "dob must be greater than 15 years ago.",

    EMAIL_REQUIRED: "email is required.",
    CATEGORY_EXISTS: "category is exists.",
    ADMIN_NOT_FOUND: "user is not admin",
    ADMIN_DELETE: "admin is delete successfully",
    NOT_ACTIVE: "admin is not active",

    ADMINID_MISSING: "adminid is missing.",
    ADMIN_DOES_NOT_MATCH: "admin role does not match.",

    REGISTER_SUCCESS: "register successfully.",
    ADMIN_LOGIN: "admin login successfully.",
    LOGOUT_SUCCESS: "logout successfully.",
    SUCCESS: "submit successfully.",
    UPDATE: "update successfully.",
    CANCEL: "cancel successfully.",
    DELETE: "deleted successfully.",
    REPORTED_SUCCESS : "reported successfully",
    REPORT_NOT_FOUND : "reported not found.",
    REFERAL_CODE_ALREADY_EXISTS: "already use this code.",
    REFERAL_CODE_NOT_FOUND: "not found.",
    ALREADY_CREATED: "this user already created referal code.",

    ADMINID_INVALID: "admin_id is invalid.",
    CONTACT_SUBMITED: "contact form submitted successfully.",
    SUPER_ADMIN_ALREADY_EXISTS: "super admin already exists.",

    WALLET_OLD_PIN_INVALID: "invalid old pin.",
    PIN_ALREADY_SET: "pin already set.",
    WALLET_NOT_FOUND: "wallet not found.",
    WALLET_PIN_INVALID: "invalid pin.",

    WALLET_SYNCHRONIZE_PIN_INVALID: "synchronize pin is required or invalid",
    POLICY_CREATED: "policy created successfully",
    POLICY_UPDATED: "policy updated successfully",

    USER_NOT_VERIFIED: "user is not verified.",

    BUSINESSID_MISSING: "business id is missing",
    BUSINESS_NOT_FOUND: "business is not found",

    USER_ALREADY_REQUESTED: "user already requested recipient",
    RECIPIENT_ALREADY_REQUESTED: "recipient already requested user",
    REQUEST_APPROVED: "request approved",
    REQUEST_REJECTED: "request rejeceted",
    REQUEST_SENT: "request sent",
    REQUEST_SENT_USER: "we have sent request to the user please wait till the user request acceptance.",
    USER_CAN_TRACK_NOW: "you can track now",
    REQUEST_ALREADY_SENT_USER: "we have already requested to the user please wait till the user request acceptance.",
    ASSIGNED_WITH_OTHER_STATUS: "request assign with other status",

    EVENT_NOT_FOUND : "event is not found",

    MOBILE_SHOULD_BE_UNIQUE: "mobile should be unique",
    EMAIL_SHOULD_BE_UNIQUE: "email should be unique",
    INVALID_DATA: "invalid data",

    NOT_TRUSTED: "not trusted",
    AVG_TRUSTED: "average trusted",
    NOT_VERIFIED: "not verfied",
    ABOVE_AVERAGE_TRUST: "above average trusted",
    ALMOST_TRUST: "almost trusted",
    SUPER_TRUSTED: "super trusted",

    ADDRESS_NOT_FOUND: "address not found",
    EMPLOYEE_NOT_FOUND: "employee not found.",
    NOT_PERMISSION: "you have not permission.",
    ACTIVITIES_LOG_NOT_FOUND: "your activities log not found.",

    FRIENDS_NOT_FOUND: "friends not found",
    ALREADY_ADDED_LINKING: "friends already has status",

    ALREADY_BLOCKED: "user is already blocked.",
    BLOCK_SUCCESS: "user has been blocked.",
    UNBLOCKED_SUCCESS: "user has been unblocked.",

    CATEGORY_ALREADY_EXITS: "name already in use",
    TRUST_ALREADY_EXITS: "trust already in use",
    YOUR_LIMIT: "out of limit",
    YOUR_LIMIT_PENDING: "you still have limit left.",
    TRUST_NOT_FOUND: "trust not found",
    USER_REQUEST_REJECTED: "this user request is rejected.",
    ALREADY_SEND_REQUEST: "you have already submitted request. please wait for admin review.",
    TRACE_USER_NOT_FOUND: "trace user not found.",
    REQUEST_USER_NOT_FOUND: "request user not found",
    REQUEST_NOT_FOUND: "request not found",

    GROUP_CREATE_SUCCESS: "group created successfully",
    GROUP_UPDATE_SUCCESS: "group updated successfully",
    ROLE_NOT_FOUND: "role not found.",
    DATA_NOT_FOUND: "data not found",
    CONFIGURABLE_NOT_FOUND: "configurable fields not found.",
    AFTER_TODAY: "please enter date after today.",
    AFTER_START_DATE: "please enter date after start date.",
    EMPLOYEE_UNAVAILABLE: "employee unavailable successfully.",
    LIMIT_NOT_SET: "admin are not added limit.",
    BUSINESS_APPROVED: "business approved successfully.",
    BUSINESS_REJECTED: "business rejected successfully",
    GROUP_NOT_FOUND: "group not found",
    ADMIN_ERROR: "please contact group admin",
    MEMBER_ADDED: "member added successfully",
    MEMBER_REMOVED: "member removed successfully",
    MEMBER_LEAVE: "you leave group successfully",
    ALREADY_A_MEMBER: "already a member.",
    ALREADY_AN_ADMIN: "already an admin",
    MEMBER_NOT_FOUND : "member not found",
    USER_INACTIVE: "user account inactive successfully",
    USER_ACTIVE: "user active successfully",
    ALREADY_INACTIVE: "this user account is already inactive",
    SELFIE_VERIFY_SUCCESSFULLY: "selfie verify successfully.",
    ADDRESS_ADDED_SUCCESSFULLY: "address added successfully.",
    STATUS_ACCEPTED: "employee accepted successfully.",
    STATUS_REJECTED: "employee rejected successfully.",
    STATUS_AVAIlABLE_ACCEPTED: "employee unavailable request accepted successfully.",
    STATUS_AVAIlABLE_REJECTED: "employee unavailable request rejected successfully.",
    BUSINESS_UPDATED_SUCCESSFULLY: "business update successfully.",
    REQUEST_ALREADY_SENT : "you have already submitted request.",
    SELFIE_NOT_VERIFY: "selfie is not verified.",
    SELFIE_VERIFY: "selfie is verified.",
    ALREADY_SEND_INVITATION: "already send invitation.",
    EVENT_INVITATION_SEND: "event invitation send successfully.",
    ALREADT_REQUEST_EVENT: "you are already request to block this event.",
    INVITATION_APPROVED: "invitation approved successfully.",
    INVITATION_REJECTED: "invitation rejected successfully.",
    UNLINK_SUCCESS :"user unlinked successfully.",
    ID_ALREADY_USED : "id is already in use, please use different id.",
    TRACE_USER_DELETE: "trace user deleted successfully.",
    APPROVE: "approved successfully.",
    UNLIKE_SUCCESSFULLY: "unlike successfully.",
    LIKE_SUCCESSFULLY: "like successfully.",
    COMMENT_SUCCESSFULLY: "comment added successfully.",
    POST_NOT_FOUND : "post is not found.",
    COMMENT_NOT_FOUND: "comment is not found.",
    COMMENT_REMOVED: "comment remove successfully.",
    ALREADT_REQUEST_POST: "you are already request to block this post.",
    POST_UPDATED: "post updated successfully.",
    POST_ALREADY_DELETE: "this post is already deleted.",
    POST_DELETE: "post deleted successfully.",
    CATEGORY_NOT_FOUND: "category is not found.",
    NAME_ALREADY_EXIST: "chat category name already exits.",
    REFERANCE_DELETE: "referance delete successfully.",
    REFERENCES_NOT_FOUND: "referance not found.",
    
    REPORT_DELETED: "report deleted successfully.",
    NOTIFICATION_UPDATED: "notification status updated.",
    SUBJECT_DELETED: "subject deleted successfully.",
    SUBJECT_UPDATED: "subject updated successfully.",
    SUBJECT_EXIST: "subject exist with this report type successfully.",
    USER_DELETE: "user deleted successfully.",
    DELETE_REQUEST: "delete request send successfully.",
    BUSINESS_DELETE: "business deleted successfully.",
    REQUEST_CANCEL: "request cancel successfully.",

    APPROVE_BUSINESS: "your business request has been approved by the admin.",
    REJECT_BUSINESS: "your business request has been rejected by the admin.",
    THANK_YOU:"thank you for being a part of beɘmz.",
    BEEMZ_CONTACT:"if you require any further assistance, please contact us at support@beemxyz.com.",
    RECIEVED_MESSAGE:"you've received this message because your email address has been registered with beɘmz.",
    SEND_CODE_MESSAGE:"please do not share this code with anyone.if this wasn't you, someone may have mistyped their email address. keep this code to yourself and no other action is needed at this moment.",

    SINGLE_REQUEST:{
        TITLE:'link request',
        BODY:':name link request',
    },
    SINGLE_REQUEST_APPROVE:{
        TITLE:'link request approved',
        BODY:':name approved your link request',
    },
    SINGLE_REQUEST_REJECT:{
        TITLE:'link request rejected',
        BODY:':name rejected your link request',
    },
    BUSINESS_REQUEST:{
        TITLE:'business link request',
        BODY:':name request you for :business link',
    },
    REFERENCE_REQUEST:{
        TITLE:'reference request',
        BODY:':name reference request',
    },
    REFERENCE_REQUEST_APPROVE:{
        TITLE:'reference request approved',
        BODY:':name approved your reference request',
    },
    REFERENCE_REQUEST_REJECT:{
        TITLE:'reference request rejected',
        BODY:':name rejected your reference request',
    },
    EMPLOYEE_REQUEST:{
        TITLE:'employee request',
        BODY:':name request you for employee in business :business',
    },
    EMPLOYEE_REQUEST_APPROVE:{
        TITLE:'employee approved request',
        BODY:':name approved employee request for :designation in business :business',
    },
    EMPLOYEE_REQUEST_REJECT:{
        TITLE:'employee reject request',
        BODY:':name rejected employee request for :designation in business :business',
    },
    EMPLOYEE_AVAILABILITY_REQUEST:{
        TITLE:'employee availability request',
        BODY:':name request you for un-availability in business :business',
    },
    EMPLOYEE_AVAILABILITY_APPROVE:{
        TITLE:'availability request approved',
        BODY:':business approved your availability request',
    },
    EMPLOYEE_AVAILABILITY_REJECT:{
        TITLE:'availability request rejected',
        BODY:':business reject your availability request',
    },
    PARENT_VERIFICATION_REQUEST:{
        TITLE:'parent verification request',
        BODY:'parent verification need for user :name',
    },
    PARENT_VERIFICATION_APPROVE:{
        TITLE:'parent verification approved',
        BODY:':name approved your parent verification',
    },
    PARENT_VERIFICATION_REJECT:{
        TITLE:'parent verification rejeceted',
        BODY:':name has denied to approve parent verification',
    },
    TRUST_LEVEL_UPDATE:{
        TITLE:'trust level update',
        BODY:':message',
    },
    
    PERSONAL_MESSAGE:{
        TITLE:':name message',
        BODY:':message',
    },
    GROUP_MESSAGE:{
        TITLE:':name in :group message',
        BODY:':message',
    },
    BUSINESS_MESSAGE:{
        TITLE:':business message',
        BODY:':message',
    },

    TRACE_USER_REQUEST:{
        TITLE:'trace user request',
        BODY:':name request you for trace',
    },
    TRACE_USER_REQUEST_APPROVE:{
        TITLE:'trace user request approved',
        BODY:':name approved your trace user request',
    },
    TRACE_USER_REQUEST_REJECT:{
        TITLE:'trace user request rejeceted',
        BODY:':name has denied your trace user request',
    },
    TRACE_END_USER_ACCESSS_LOCATION:{
        TITLE:'live location request',
        BODY:':name requested your current location',
    },
    TRACE_END_USER_WANT_LOCATION:{
        TITLE:'live location request',
        BODY:':name requested your current location',
    },
    LOCATION_NOTIFICATION_FOR_OFFLINE_USER:{
        TITLE:'update location log and trust level',
        BODY:'please open beamz and always keep it open in the background to ensure accurate and updated location logs.',
    },
    REPLY_TO_USER_REPORT:{
        TITLE:'Report response',
        BODY:':name',
    },

}